# Generated by Django 5.0.2 on 2024-03-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
