# Generated by Django 4.0 on 2024-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_payment_stripe_price_id_payment_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
