# Generated by Django 4.0 on 2024-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
