# Generated by Django 4.0 on 2024-03-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_course_product_id_lesson_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_product_id',
        ),
    ]
